version: '3'
services:

  #web app
  laravel_web:
    build:
      context: ./
    tty: true
    expose:
      - "80"
    ports:
      - 80:80
    volumes:
      - ./:/var/www/app
    container_name: laravel_web
    links:
      - laravel_db

  #database
  laravel_db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    container_name: laravel_db

volumes:
  db_data: {}
